[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-codspeed"
dynamic = ["version"]
description = "Pytest plugin to create CodSpeed benchmarks"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
authors = [{ name = "Arthur Pastel", email = "arthur.pastel@gmail.com" }]
keywords = ["avalanche", "benchmark", "measurement", "performance", "pytest"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Benchmark",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = ["cffi>=1.0.0", "pytest>=3.8"]

[project.optional-dependencies]
dev = ["black", "flake8", "hatchling", "mypy", "pytest", "pytest-cov"]

[project.entry-points]
pytest11 = { codspeed = "pytest_codspeed.plugin" }

[tool.hatch.version]
path = "src/pytest_codspeed/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["/src"]
