name: benchmarks
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3

      - run: conda install pytest

      - run: pip install pytest-codspeed

      - uses: CodSpeedHQ/action@
        with:
          run: pytest tests/benchmarks/ --codspeed
