name: benchmarks
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install custom version of pyperformance
        run: pip install "git+https://github.com/mdboom/pyperformance@codspeed#egg=pyperformance"
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: pyperformance run --fast --loops 0 --warmups 0
