name: CodSpeed
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install valgrind
        run: sudo apt-get install valgrind -y
      - name: Build the wheel
        run: uv build --wheel --out-dir dist/
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

  benchmarks:
    name: Run benchmarks
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist
      - name: Install local version of pytest-codspeed
        run: pip install dist/*.whl
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: pytest tests/benchmarks/ --codspeed
