name: CodSpeed
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install local version of pytest-codspeed
        run: pip install .
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: pytest tests/benchmarks/ --codspeed
