name: Release on tag

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
            python-version: "3.11"

      - name: Install dependencies
        run: pip install hatch

      - name: Build the library
        run: hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create a draft release
        run: |
          NEW_VERSION=$(hatch project metadata | jq -r '.version')
          gh release create v$NEW_VERSION --title "v$NEW_VERSION" --generate-notes -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
