name: Release on tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build-wheels:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-24.04
            arch: x86_64
          - runs-on: buildjet-2vcpu-ubuntu-2204-arm
            arch: arm64
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update APT cache # BuildJet doesn't cache APT well
        if: startsWith(matrix.platform.runs-on, 'buildjet-')
        run: sudo apt-get update

      - name: Install valgrind
        run: sudo apt-get install valgrind -y

      - name: Build the library
        run: uv build --wheel --out-dir dist/
        env:
          PYTEST_CODSPEED_FORCE_EXTENSION_BUILD: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}-${{ matrix.platform.arch }}
          path: dist/*.whl

  publish:
    needs: build-wheels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/

      - name: Build the source dist
        run: uv build --sdist --out-dir dist/

      - name: List artifacts
        run: ls -al dist/*

      - if: github.event_name == 'push'
        name: Publish to PyPI
        run: uv publish --trusted-publishing=always dist/*

      - if: github.event_name == 'push'
        name: Create a draft release
        run: |
          VERSION="${{ github.ref_name }}"
          gh release create $VERSION --title $VERSION --generate-notes -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
